In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["Alice","Bob","Claire"],
    "age":[25,30,27],
    "city":["France","Mauritius","Finland"]
} , index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

     name  age       city
a   Alice   25     France
b     Bob   30  Mauritius
c  Claire   27    Finland

name          Bob
age            30
city    Mauritius
Name: b, dtype: object

In [ ]:
print(df.loc[df["age"]>25,["name","age"]])

     name  age
b     Bob   30
c  Claire   27

In [ ]:
print(df.iloc[[0,1]]) #selection of rows and columns

     name  age     city
a   Alice   25   France
c  Claire   27  Finland

In [ ]:
print(df.iloc[[0,2],[1,2]]) #select rows and columns by position

   age     city
a   25   France
c   27  Finland

In [12]:
print(df.iloc[[0,1]])

     farm   crop  area_hectares  prouction_tonne
0  farm a  wheat             10               30
1  farm b   rice             15               60

In [13]:
df["crop"]

0    wheat
1     rice
2    wheat
3    maize
Name: crop, dtype: object

In [10]:
import pandas as pd
data={
    "farm":["farm a","farm b","farm c","farm d"],
    "crop":["wheat","rice","wheat","maize"],
    "area_hectares":[10,15,8,12],
    "prouction_tonne":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     farm   crop  area_hectares  prouction_tonne
0  farm a  wheat             10               30
1  farm b   rice             15               60
2  farm c  wheat              8               24
3  farm d  maize             12               36

In [14]:
df.head()

     farm   crop  area_hectares  prouction_tonne
0  farm a  wheat             10               30
1  farm b   rice             15               60
2  farm c  wheat              8               24
3  farm d  maize             12               36

In [16]:
df.head(2) #first two rows

     farm   crop  area_hectares  prouction_tonne
0  farm a  wheat             10               30
1  farm b   rice             15               60

In [18]:
df.tail(2) #bottom two rows

     farm   crop  area_hectares  prouction_tonne
2  farm c  wheat              8               24
3  farm d  maize             12               36

In [20]:
df.info() #gives basic information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_hectares    4 non-null      int64
 3   prouction_tonne  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [22]:
df.describe() #basic summary in statistic form

       area_hectares  prouction_tonne
count       4.000000         4.000000
mean       11.250000        37.500000
std         2.986079        15.779734
min         8.000000        24.000000
25%         9.500000        28.500000
50%        11.000000        33.000000
75%        12.750000        42.000000
max        15.000000        60.000000

In [30]:
#add a new column (yield)
#yield=production÷area
df["yield_tonne_per_hectare"]=df["prouction_tonne"]/df["area_hectares"]
print(df)

     farm   crop  area_hectares  prouction_tonne  yield_tonne_per_hectare
0  farm a  wheat             10               30                      3.0
1  farm b   rice             15               60                      4.0
2  farm c  wheat              8               24                      3.0
3  farm d  maize             12               36                      3.0

In [27]:
print(df.iloc[[1,3]])

     farm   crop  area_hectares  prouction_tonne  yield_tonne_per_hectare
1  farm b   rice             15               60                      4.0
3  farm d  maize             12               36                      3.0

In [29]:
df.describe()

       area_hectares  prouction_tonne  yield_tonne_per_hectare
count       4.000000         4.000000                     4.00
mean       11.250000        37.500000                     3.25
std         2.986079        15.779734                     0.50
min         8.000000        24.000000                     3.00
25%         9.500000        28.500000                     3.00
50%        11.000000        33.000000                     3.00
75%        12.750000        42.000000                     3.25
max        15.000000        60.000000                     4.00

In [32]:
print(df.iloc[[1,3],[0,1,2]])

     farm   crop  area_hectares
1  farm b   rice             15
3  farm d  maize             12

In [33]:
print(df.iloc[[1,3],[0,1,2,3]])

     farm   crop  area_hectares  prouction_tonne
1  farm b   rice             15               60
3  farm d  maize             12               36

In [34]:
df.loc[[1,3],["farm","crop"]]

     farm   crop
1  farm b   rice
3  farm d  maize

In [37]:
#filter data
#farms growing wheat
print(df["crop"]=="wheat")
print()
wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

0     True
1    False
2     True
3    False
Name: crop, dtype: bool

     farm   crop  area_hectares  prouction_tonne  yield_tonne_per_hectare
0  farm a  wheat             10               30                      3.0
2  farm c  wheat              8               24                      3.0

In [38]:
#farms with yield greater than 3
high_yield=df[df["yield_tonne_per_hectare"]>3]
print(high_yield)

     farm  crop  area_hectares  prouction_tonne  yield_tonne_per_hectare
1  farm b  rice             15               60                      4.0

In [43]:
#sort the farms by highest production
sorted_df=df.sort_values(by="prouction_tonne",ascending=False)
print(sorted_df)

     farm   crop  area_hectares  prouction_tonne  yield_tonne_per_hectare
1  farm b   rice             15               60                      4.0
3  farm d  maize             12               36                      3.0
0  farm a  wheat             10               30                      3.0
2  farm c  wheat              8               24                      3.0

In [42]:
#groupBy operation -average yield per crop
avg_yield=df.groupby("crop")["yield_tonne_per_hectare"].mean()
print(avg_yield)

crop
maize    3.0
rice     4.0
wheat    3.0
Name: yield_tonne_per_hectare, dtype: float64

In [53]:
lyrics=("if you hold me without  hurting me you will be the first who ever did lalalalalal - lana del rey")
print(lyrics)

if you hold me without  hurting me you will be the first who ever did lalalalalal - lana del rey